apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  external_services:
    tracing:
      enabled: true
      in_cluster_url: "http://jaeger-query.istio-system.svc.cluster.local:16685"
      use_grpc: true
      url: "http://jaeger-query.istio-system.svc.cluster.local:16686"